name: notesapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.2.1
environment:
  sdk: '>=2.18.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  localstorage: ^4.0.0+1
  cupertino_icons: ^1.0.2
  firebase: ^9.0.0
  firebase_auth: ^4.2.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  google_sign_in: ^5.4.2
  google_sign_in_ios: ^5.5.1
  intl: ^0.18.0
  local_auth: ^2.1.3
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter dependencides
flutter:
# material design
  uses-material-design: true

# Assets
  assets:
    - android/assets/images/
  # Fonts 
  fonts:
    - family: lato
      fonts:
        - asset: android/assets/lato/Lato-Regular.ttf
        - asset: android/assets/lato/Lato-Bold.ttf
        - asset: android/assets/lato/Lato-BoldItalic.ttf
        - asset: android/assets/lato/Lato-Thin.ttf
        - asset: android/assets/lato/Lato-ThinItalic.ttf
        - asset: android/assets/lato/Lato-Black.ttf
        - asset: android/assets/lato/Lato-BlackItalic.ttf
        - asset: android/assets/lato/Lato-Italic.ttf
        - asset: android/assets/lato/Lato-Light.ttf
        - asset: android/assets/lato/Lato-LightItalic.ttf
          weight: 800

